service: wishlist

plugins:
- serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  versionFunctions: false
  environment:
    dbname: dfviun0r9lhn0i
    user: ${opt:user}
    password: ${opt:password}
    host: ec2-54-83-202-132.compute-1.amazonaws.com
    port: 5432

functions:
  hello:
    handler: handler.hello
    events: 
      - http:
          path: users/create
          method: get

  claimGift:
    handler: functions/wishlist_handler.claim_gift
    events:
      - http:
          path: claim/{id}
          method: post

